### PR TITLE
Change from &str to AsRef<[u8]> in builder

### PR DESCRIPTION
**Pull request by aria-aghaei**
Changes from &str to AsRef in the CommandBuilder. For #8

Let me know if you want me to add a test case or have suggestions.

### CODE REVIEW

**Comment by diondokter** [comment]
Hey there, thanks for the PR!

Could you add this change to the changelog? Just add a new "unreleased" header to the list and out this under there.

Are you in a hurry to get this released on crates io?

**Comment by aria-aghaei** [comment]
Sure, I can add it to the changelog. I'm not in a hurry, you can merge whenever

**Comment by diondokter** [comment]
Thanks!

**Comment by diondokter** [comment]
Now released as 0.5.4

**Pull request merged**
