### PR TITLE
add support for optional parser parameters

### PR DESCRIPTION
**Pull request by tarfu**
This should be a discussion starter for an implementation for #7.
It is mostly a copy of the existing methods and tweaking them a bit.

I would also replace the implementation of the none optional counterparts with the optional ones and just wrap it with a None check.

### CODE REVIEW

**Comment by diondokter** [comment]
Hi! Thanks for working on this :)

#7 didn't really talk about this, but more like if an at command has e.g. either 3 or 6 parameters depending on some condition.

However, the thing you're implementing here also does happen so it's a good feature to have.
One thing though is that I don't really like the amount of duplicated code.
It would be nice if it could be refactored so that the non-optional functions would simply use the optional functions.
That way going forward the maintenance will be easier.

**Comment by tarfu** [comment]
The way of the refactoring was chosen because if we used the optional methods directly we would already have added the response to the tucat and this would break the API as the non-optional would also return an `Option`.

**Review by diondokter — COMMENTED** [review]
Ah I see what you mean and what you've done here. Very nice!

**Review by diondokter — CHANGES_REQUESTED** [review]
Sorry that this fell off my radar a bit. Could you add this to the changelog? Just add an "Unreleased" section to the top of the list and add this PR as a bullet point under it.

**Comment by diondokter** [comment]
Oh that was quick, thanks!

Once the other open PR is merged, I'll make a new release :)

**Pull request merged**
